/**
 * simulation-constants.ts
 * AUTO-GENERATED by scrape-baselines.ts — do not edit manually.
 * To regenerate: npx ts-node scrape-baselines.ts
 *
 * Last fetched: 2026-03-08T06:08:41.752Z
 */

// ─────────────────────────────────────────────────────────────────
// CRIME / REENTRY
// source: Montgomery_Crime_7days_2026-03-04.csv (local CSV)
// ─────────────────────────────────────────────────────────────────

export const WEEKLY_INCIDENTS = 143
export const ANNUAL_INCIDENTS_ESTIMATE = WEEKLY_INCIDENTS * 52  // 7,436/yr

/** source: AL DOC Annual Report 2023 (fallback) */
export const BASE_RECIDIVISM_RATE = 0.32

export const AVERAGE_INCARCERATION_COST = 28_600  // Vera Institute, Alabama FY2022

/**
 * Reentry pipeline: ~18% of annual incidents → reentry cohort
 * CSV: 143/wk × 52 × 0.18 ≈ 1,338
 */
export const TARGET_POPULATION = 1_338
export const EMPLOYMENT_CONVERSION_RATE = 0.65

// ─────────────────────────────────────────────────────────────────
// DEMOGRAPHICS  source: Census ACS 2023
// ─────────────────────────────────────────────────────────────────

/** source: Census ACS 2023 B01003 — Montgomery County, AL */
export const MONTGOMERY_POPULATION = 224980

/** source: Census ACS 2023 B01001 — ages 25–34 */
export const YOUNG_ADULT_POPULATION = 29861

/** source: Census ACS 2023 B25010 */
export const AVG_HOUSEHOLD_SIZE = 2.33

/** source: Census ACS 2023 B19013 — Montgomery County median HH income */
export const MEDIAN_HOUSEHOLD_INCOME = 60739

/** source: Census ACS 2023 B17001 */
export const POVERTY_RATE = 0.1700  // 17.0%

// ─────────────────────────────────────────────────────────────────
// FISCAL
// ─────────────────────────────────────────────────────────────────

/**
 * Per-capita annual local tax contribution
 * = MEDIAN_HOUSEHOLD_INCOME × 0.65 (per-capita adj) × 8.5% (AL+city tax)
 * source: Census ACS 2023 (live)
 */
export const AVERAGE_ANNUAL_TAX = 3356

/**
 * NPV of lifetime local tax contribution per retained young adult (25yr, 0.72 discount)
 * source: Census ACS 2023 (live)
 */
export const LIFETIME_TAX_CONTRIBUTION = 60405

export const CHILD_GENERATION_MULTIPLIER = 1.4  // second-generation tax contribution multiplier

// ─────────────────────────────────────────────────────────────────
// YOUTH RETENTION
// source: IRS SOI Migration Data 2021→2022, Montgomery County
// ─────────────────────────────────────────────────────────────────

export const BASELINE_RETENTION_RATE = 0.48  // net outmigration implies ~48% annual retention

// ─────────────────────────────────────────────────────────────────
// HOUSING  source: Montgomery_Construction_Permit.csv (local CSV)
// ─────────────────────────────────────────────────────────────────

export const HOUSING_PIPELINE_UNITS = 514
export const CONSTRUCTION_PIPELINE_VALUE_M = 218.8
export const NEW_RESIDENTIAL_PERMITS = 120
export const NEW_COMMERCIAL_PERMITS = 32

/** source: HUD FMR 2024 (fallback) */
export const MEDIAN_2BR_RENT = 1050

// ─────────────────────────────────────────────────────────────────
// LABOR  source: BLS LAUS 2024 (fallback)
// ─────────────────────────────────────────────────────────────────

export const UNEMPLOYMENT_RATE_PCT = 5.2

// ─────────────────────────────────────────────────────────────────
// CRIME BREAKDOWN  source: Montgomery_Crime_7days_2026-03-04.csv
// ─────────────────────────────────────────────────────────────────

export const CRIME_BREAKDOWN = {
  THEFT:            51,
  DOMESTIC:         17,
  CRIMINAL:         16,
  BURGLARY:         12,
  ASSAULT:          12,
  HARASSMENT:       11,
  DISCHARGING:       6,
  ROBBERY:           4,
  MENACING:          4,
  ASSAULT_DOMESTIC:  3,
  HOMICIDE:          1,
} as const

export const VIOLENT_CRIMES_WEEKLY  = 37
export const PROPERTY_CRIMES_WEEKLY = 79
